networks:
  ai-infra:
    name: ai-infra-net
    external: true
  ai-public:
    name: ai-public-net
    external: true

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    profiles: ["monitoring"]
    restart: unless-stopped
    networks:
      - ai-infra
      - ai-public
    ports:
      - "8082:8080"   # optional direct access: http://127.0.0.1:8082
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.localhost`)"
      - "traefik.http.routers.cadvisor.entrypoints=web"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"


  node-exporter:
    image: prom/node-exporter:v1.10.2
    profiles: ["monitoring"]
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro
    ports:
      - "9100:9100"
    networks:
      - ai-infra
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.51.0
    profiles: ["monitoring"]
    restart: unless-stopped
    networks:
      - ai-infra
      - ai-public
    ports:
      - "9090:9090"   # optional direct access: http://127.0.0.1:9090
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../volumes/prometheus:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:10.4.0
    profiles: ["monitoring"]
    restart: unless-stopped
    networks:
      - ai-infra
      - ai-public
    ports:
      - "3001:3000"   # optional direct access: http://127.0.0.1:3001
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ../volumes/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
